branches:
  only:
    - master

services:
  - docker

language: java
jdk: openjdk8

install: mvn --settings settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn --settings settings.xml clean install

cache:
  directories:
    - $HOME/.m2

after_success:
  - sh ./travis/heroku-deploy.sh
  - mvn coveralls:report
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECTKEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_LOGIN

notifications:
  email:
    recipients:
      - yurqaa@mail.ru
    on_failure: always