sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

script: mvn clean install

cache:
  directories:
  - $HOME/.m2

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- mvn dockerfile:build
- mvn dockerfile:push
- mvn coveralls:report
- mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECTKEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_LOGIN

notifications:
  email:
    recipients:
      - yurqaa@mail.ru
    on_failure: always
