version: '3.8'

services:

  anime-checker:
    image: registry.heroku.com/anime-checker/web
    container_name: anime-checker
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      FTS_BASIC_AUTH: ${FTS_BASIC_AUTH}
      MS_BASIC_AUTH: ${MS_BASIC_AUTH}