version: '3.8'

services:

  anime-checker:
    image: nasirov/anime-checker
    container_name: anime-checker
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      PORT: ${PORT}