version: '3.8'

services:

  anime-checker:
    image: nasirov/anime-checker
    container_name: anime-checker
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      FTS_BASIC_AUTH: ${FTS_BASIC_AUTH}
      MS_BASIC_AUTH: ${MS_BASIC_AUTH}
      SS_BASIC_AUTH: ${SS_BASIC_AUTH}