{{- $replicaCount := .Values.replicaCount | int -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "anibozu.metadata" . | indent 2 }}
  labels:
    {{- include "anibozu.labels" . | indent 4 }}
  annotations:
    {{- include "anibozu.annotations" . | indent 4 }}
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: {{ .Values.docker.progressDeadlineSeconds }}
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      {{- include "anibozu.labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      {{- if gt $replicaCount 1 }}
      maxSurge: 0
      maxUnavailable: 1
      {{- else }}
      maxSurge: 1
      maxUnavailable: 0
      {{- end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "anibozu.labels" . | indent 8 }}
      annotations:
        {{- include "anibozu.annotations" . | indent 8 }}
        {{- include "vault.injector.annotations" . | indent 8 }}
    spec:
      {{- include "vault.injector.service-account" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.docker.containerPort }}
              protocol: TCP
            - name: jmx
              containerPort: 3637
              protocol: TCP
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
            initialDelaySeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            timeoutSeconds: 1
            failureThreshold: 30
            successThreshold: 1
            periodSeconds: 4
            initialDelaySeconds: 45
      {{- if .Values.docker.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.docker.pullSecretName }}
      {{- end }}