{{- if .Values.ingress -}}
{{- $name := .Chart.Name -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $hosts := .Values.ingress.hosts -}}
{{- $tls := .Values.ingress.tls -}}
{{- $tlsHosts := .Values.ingress.tls.hosts -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "anibozu.metadata" . | indent 2 }}
  labels:
    {{- include "anibozu.labels" . | indent 4 }}
  annotations:
    {{- include "anibozu.annotations" . | indent 4 }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
{{- if $tls }}
  tls:
  {{- with $tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range  $ingressPaths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- end }}