{{- if .Values.ingress -}}
{{- $name := include "chart.name" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $annotations := .Values.ingress.annotations -}}
{{- $hosts := .Values.ingress.hosts -}}
{{- $tls := .Values.ingress.tls -}}
{{- $tlsHosts := .Values.ingress.tls.hosts -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "chart.name" . }}-internal
  {{- include "extended_labels" . | indent 2 }}
  annotations:
  {{- with $annotations }}
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{- if $tls }}
  tls:
  {{- with $tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range  $ingressPaths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- end }}