apiVersion: v1
kind: Service
metadata:
  {{- include "anibozu.metadata" . | indent 2 }}
  labels:
    {{- include "anibozu.labels" . | indent 4 }}
  annotations:
    {{- include "anibozu.annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "anibozu.labels" . | indent 4 }}