apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "anibozu.metadata" . | indent 2 }}
  labels:
    {{- include "anibozu.labels" . | indent 4 }}
  annotations:
    {{- include "anibozu.annotations" . | indent 4 }}