spring:
  application:
    name: anime-checker

starter-reactive-services:
  web-client:
    enabled: true
    connection-timeout: 2s
    read-timeout: 13s
    max-attempts: 0

application:
  fandub-support:
    enabled: ANIDUB,ANILIBRIA,ANIMEDIA,ANIMEPIK,ANYTHING_GROUP,JAMCLUB,JISEDAI,JUTSU,NINEANIME,SHIZAPROJECT,SOVETROMANTICA
  cache:
    result:
      name: result
      ttl: 5m
      max-size: 50

server:
  port: ${PORT:8080}

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR