spring:
  profiles:
    include: default

application:
  auth:
    fandub-titles-service-basic-auth: Basic YWRtaW46YWRtaW4=

animedia-feign-client:
  ribbon:
    listOfServers: https://online.animedia.tv

anidub-feign-client:
  ribbon:
    listOfServers: https://anime.anidub.life

jisedai-feign-client:
  ribbon:
    listOfServers: https://jisedai.tv

animepik-feign-client:
  ribbon:
    listOfServers: https://animepik.org

animepik-resources-feign-client:
  ribbon:
    listOfServers: https://cdn.iss.one

anilibria-feign-client:
  ribbon:
    listOfServers: https://www.anilibria.tv

nine-anime-feign-client:
  ribbon:
    listOfServers: https://www12.9anime.to

jutsu-feign-client:
  ribbon:
    listOfServers: https://jut.su

mal-feign-client:
  ribbon:
    listOfServers: https://myanimelist.net

fandub-titles-service-feign-client:
  ribbon:
    listOfServers: https://localhost:8089