application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter:
      enabled: true
  cache:
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  common:
    enable-build-url-in-runtime:
      ANIDUB: false
      ANILIBRIA: false
      ANIMEDIA: false
      ANIMEPIK: false
      JISEDAI: false
      JUTSU: false
      NINEANIME: false
      SHIZAPROJECT: false
      SOVETROMANTICA: false
      JAMCLUB: false
      ANYTHING_GROUP: false
  feign:
    enabled: false
  web-client:
    enabled: true
    compress: true
    connection-timeout: 10s
    max-attempts: 0
    min-backoff: 100ms
    max-backoff: 1s
  amqp:
    mode: MULTI_CONNECTION
    type: REACTIVE
    connections:
      QUEUES_FROM_1_TO_10:
        reply-timeout: 10s
      QUEUES_FROM_11_TO_20:
        reply-timeout: 10s

server:
  port: ${PORT}

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR