application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter:
      enabled: true
  cache:
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  common:
    enable-build-url-in-runtime:
      ANIDUB: true
      ANILIBRIA: true
      ANIMEDIA: true
      ANIMEPIK: true
      JISEDAI: true
      JUTSU: true
      NINEANIME: false
      SHIZAPROJECT: true
      SOVETROMANTICA: true
  feign:
    enabled: false
  web-client:
    enabled: true
    compress: true
    connection-timeout: 5s
    max-attempts: 5
    min-backoff: 100ms
    max-backoff: 1s

server:
  port: ${PORT}

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR