application:
  resources:
    applicationLogo: anime-checker-logo.txt
    tempFolder: temp
    tempMissedAnimediaTitles: tempMissedAnimediaTitles.json
    tempAnimediaTitlesNotFoundOnMal: tempAnimediaTitlesNotFoundOnMal.json
    tempExAnnouncements: exAnnouncements.json
  urls:
    animedia-urls:
      online-animedia-tv: https://online.animedia.tv/
    mal-urls:
      myAnimeList-net: https://myanimelist.net
      cdn-myAnimeList-net: https://cdn.myanimelist.net/
    nine-anime-urls:
      nine-anime-to: https://9anime.to
    anidub-urls:
      anidub-site-url: https://anime.anidub.life/
    jisedai-urls:
      jisedai-site-url: https://jisedai.tv/
    animepik-urls:
      animepik-url: https://animepik.org/
      animepik-resources-url: https://cdn.iss.one
    anilibria-urls:
      anilibria-url: https://www.anilibria.tv/
  services:
    applicationLogoPrinter-enabled: true
  cron:
    resources-check-cron-expression: 0 0/30 * * * ?
  cache:
    data-list-info:
      name: dataListInfo
      ttl: 300
      max-entity-count: 200
    mal:
      name: mal
      ttl: 300
      max-entity-count: 50
    github:
      name: github
      ttl: 3600
      max-entity-count: 5
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  github-auth:
    token: ${GITHUB_ACCESS_TOKEN}
  sse:
    timeout-in-min: 5
  animedia:
    search-list-max-size: 900
    request-limit: 100
  mal:
    offset-step: 300
  fandub:
    disabled: NINEANIME
  github:
    resources:
      animedia-titles: animediaTitles.json
      anidub-titles: anidubSiteTitles.json
      jisedai-titles: jisedaiSiteTitles.json
      animepik-titles: animepikTitles.json
      anilibria-titles: anilibriaSiteTitles.json

server:
  port: ${PORT}

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 2
  retryableStatusCodes: 429, 403, 504, 503

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    com.netflix: ERROR
    nasirov.yv: DEBUG