spring:
  application:
    name: anibozu

starter-reactive-services:
  web-client:
    read-timeout: 10s
    max-attempts: 0

starter-cache:
  enabled: true
  type: CAFFEINE
  caches:
    - name: ${application.cache-props.github-cache-name:}
      expire-after-write: 24h

application:
  cache-props:
    cache-on-startup: true
    github-cache-name: github
    github-cache-key: fandub-anime
  mal-props:
    offset-step: 300
    limit: 50
    url: https://myanimelist.net
  enabled-fandub-sources:
    - ANI_LIBRIA
    - DREAM_CAST
    - KODIK
    - ANI_WAVE

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR