application:
  cache:
    sse:
      name: sse
      ttl: 5m
      max-size: 50
  feign:
    enabled: false
  web-client:
    enabled: true
    compress: true
    connection-timeout: 10s
    max-attempts: 0
    min-backoff: 100ms
    max-backoff: 1s

server:
  port: ${PORT}

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR