spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: anibozu

starter-reactive-services:
  web-client:
    read-timeout: 60s
    max-attempts: 1

starter-cache:
  enabled: true
  type: CAFFEINE
  caches:
    - name: ${application.cache-props.github-cache-name:}
      expire-after-write: 24h

management:
  endpoint:
    health:
      probes:
        enabled: true

application:
  cache-props:
    cache-on-startup: true
    github-cache-name: github
    github-cache-key: common-titles
  mal-props:
    offset-step: 300
    url: https://myanimelist.net
  enabled-fandub-sources:
    - ANIDUB
    - ANILIBRIA
    - ANIMEDIA
    - ANI_FILM
    - ANI_MAUNT
    - ANYTHING_GROUP
    - DREAM_CAST
    - FREE_DUB
    - KODIK
    - NINEANIME
    - SENU_PROJECT
    - SOVETROMANTICA
  ignore-next-episode-for-watch:
    - KODIK

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR