application:
  cache:
    result:
      name: result
      ttl: 5m
      max-size: 50
  feign:
    enabled: false
  web-client:
    enabled: true
    connection-timeout: 2s
    read-timeout: 13s
    max-attempts: 0

server:
  port: ${PORT}

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR