spring:
  application:
    name: anibozu
  data:
    redis:
      host: redis-master

starter-reactive-services:
  web-client:
    read-timeout: 10s
    max-attempts: 0

application:
  mal:
    url: https://myanimelist.net
    limit: 50
  security:
    admin:
      username: ${ANIBOZU_ADMIN_USERNAME}
      password: ${ANIBOZU_ADMIN_PASSWORD}
      roles: ADMIN

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR