server:
  port: 8080

application:
  web-client:
    proxy-type: HTTP
    proxy-host: localhost
    proxy-port: 8888
  external-services:
    fandub-titles-service-basic-auth: Basic YWRtaW46YWRtaW4=
    mal-service-basic-auth: Basic YWRtaW46YWRtaW4=
    fandub-titles-service-url: http://localhost:8089/
    mal-service-url: http://localhost:8087/