spring:
  redis:
    host: redis-master.default.svc.cluster.local
    port: 6379
  application:
    name: anime-checker

starter-reactive-services:
  web-client:
    enabled: true
    connection-timeout: 2s
    read-timeout: 60s
    max-attempts: 2

starter-cache:
  enabled: true
  type: REDIS
  caches:
    - name: ${application.caches-names.result-cache:}
      expire-after-write: 5m
      maximum-size: 50

management:
  endpoint:
    health:
      probes:
        enabled: true

application:
  fandub-support:
    enabled: ANIDUB,ANILIBRIA,ANIMEDIA,ANIMEPIK,ANYTHING_GROUP,JAMCLUB,JISEDAI,JUTSU,NINEANIME,SHIZAPROJECT,SOVETROMANTICA
  caches-names:
    result-cache: result-cache

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR