application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter:
      enabled: true
  cache:
    mal:
      name: mal
      ttl: 300
      max-entity-count: 50
    github:
      name: github
      ttl: 3600
      max-entity-count: 9
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  github:
    enabled: true
    token: ${GITHUB_ACCESS_TOKEN}
  sse:
    timeout-in-min: 5
  mal:
    offset-step: 300
    url: https://myanimelist.net
  auth:
    fandub-titles-service-basic-auth: ${FTS_BASIC_AUTH}

server:
  port: ${PORT}

github-feign-client:
  ribbon:
    retryableStatusCodes: 404, 500, 502, 503, 504

sovet-romantica-feign-client:
  ribbon:
    ReadTimeout: 10000

shiza-project-feign-client:
  ribbon:
    ReadTimeout: 10000

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxAutoRetries: 4
  MaxAutoRetriesNextServer: 0

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    com.netflix: ERROR
    nasirov.yv: INFO