application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter-enabled: true
  cache:
    mal:
      name: mal
      ttl: 300
      max-entity-count: 50
    github:
      name: github
      ttl: 3600
      max-entity-count: 7
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  github:
    enabled: true
    token: ${GITHUB_ACCESS_TOKEN}
  sse:
    timeout-in-min: 5
  mal:
    offset-step: 300
    url: https://myanimelist.net
  fandub:
    urls:
      ANIMEDIA: https://online.animedia.tv/
      ANIDUB: https://anime.anidub.life/
      ANILIBRIA: https://www.anilibria.tv/
      ANIMEPIK: https://animepik.org/
      JISEDAI: https://jisedai.tv/
      NINEANIME: https://www12.9anime.to/
      JUTSU: https://jut.su/

server:
  port: ${PORT}

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxAutoRetries: 2

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    com.netflix: ERROR
    nasirov.yv: DEBUG