application:
  resources:
    applicationLogo: anime-checker-logo.txt
    tempFolder: temp
    tempRawReferences: tempRawReferences.json
    tempReferencesWithInvalidMALTitleName: referencesWithInvalidMALTitleName.json
    tempExAnnouncements: exAnnouncements.json
  urls:
    animedia-urls:
      online-animedia-tv: https://online.animedia.tv/
    mal-urls:
      myAnimeList-net: https://myanimelist.net/
      cdn-myAnimeList-net: https://cdn.myanimelist.net/
  services:
    applicationLogoPrinter-enabled: true
  cron:
    resources-check-cron-expression: 0 0/30 * * * ?
  cache:
    anime-list:
      name: animeList
      ttl: 3600
      max-entity-count: 1
    title-info:
      name: titleInfo
      ttl: 300
      max-entity-count: 60
    data-list-info:
      name: dataListInfo
      ttl: 300
      max-entity-count: 200
    mal:
      name: mal
      ttl: 300
      max-entity-count: 50
    github:
      name: github
      ttl: 3600
      max-entity-count: 1
  github-auth:
    token: ${GITHUB_ACCESS_TOKEN}

server:
  port: ${PORT}

animedia-api-feign-client:
  ribbon:
    listOfServers: https://ios.animedia.tv

mal-feign-client:
  ribbon:
    listOfServers: https://myanimelist.net/

github-feign-client:
  ribbon:
    listOfServers: https://raw.githubusercontent.com

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 2
  retryableStatusCodes: 429, 403, 504

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
spring:
  application:
    name: anime-checker