spring:
  application:
    name: anibozu

starter-reactive-services:
  web-client:
    read-timeout: 10s
    max-attempts: 0

starter-cache:
  enabled: true
  type: CAFFEINE
  caches:
    - name: ${application.cache-props.github-cache-name:}
      expire-after-write: 24h

management:
  endpoint:
    health:
      probes:
        enabled: true

application:
  cache-props:
    cache-on-startup: true
    github-cache-name: github
    github-cache-key: common-titles
  mal-props:
    offset-step: 300
    url: https://myanimelist.net
  enabled-fandub-sources:
    - ANI_DUB
    - ANI_FILM
    - ANI_LIBRIA
    - ANI_MAUNT
    - ANYTHING_GROUP
    - DREAM_CAST
    - FREE_DUB
    - KODIK
    - NINE_ANIME
    - SENU_PROJECT
    - SHIZA_PROJECT
    - SOVET_ROMANTICA
  ignore-next-episode-for-watch:

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR