application:
  resources:
    applicationLogo: anime-checker-logo.txt
    tempFolder: temp
    tempMissedAnimediaTitles: tempMissedAnimediaTitles.json
    tempAnimediaTitlesNotFoundOnMal: tempAnimediaTitlesNotFoundOnMal.json
    tempExAnnouncements: exAnnouncements.json
  urls:
    animedia-urls:
      online-animedia-tv: https://online.animedia.tv/
    mal-urls:
      myAnimeList-net: https://myanimelist.net
      cdn-myAnimeList-net: https://cdn.myanimelist.net/
    nine-anime-urls:
      nine-anime-to: https://9anime.to
    anidub-urls:
      anidub-site-url: https://anime.anidub.life/
  services:
    applicationLogoPrinter-enabled: true
    animedia-service-source: site #api | site
    anidub-episode-url-service-source: site #api | site
  cron:
    resources-check-cron-expression: 0 0/30 * * * ?
  cache:
    data-list-info:
      name: dataListInfo
      ttl: 300
      max-entity-count: 200
    mal:
      name: mal
      ttl: 300
      max-entity-count: 50
    github:
      name: github
      ttl: 3600
      max-entity-count: 2
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  github-auth:
    token: ${GITHUB_ACCESS_TOKEN}
  sse:
    timeout-in-min: 5
  animedia:
    search-list-max-size: 900
    request-limit: 100
  mal:
    offset-step: 300
  fandub:
    disabled: NINEANIME
  github:
    resources:
      animedia-titles: animediaTitles.json
      anidub-api-titles: anidubApiTitles.json
      anidub-site-titles: anidubSiteTitles.json

server:
  port: ${PORT}

animedia-api-feign-client:
  ribbon:
    listOfServers: https://ios.animedia.tv

animedia-site-feign-client:
  ribbon:
    listOfServers: https://online.animedia.tv

mal-feign-client:
  ribbon:
    listOfServers: https://myanimelist.net

github-feign-client:
  ribbon:
    listOfServers: https://raw.githubusercontent.com

nine-anime-feign-client:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 10
    listOfServers: https://9anime.to,https://9anime.tv,https://9anime.live,https://9anime.life,https://9anime.love,https://9anime.nl,https://9anime.one,https://9anime.page,https://9anime.ru,https://9anime.video

anidub-api-feign-client:
  ribbon:
    listOfServers: ${ANIDUB-API-URL}

anidub-site-feign-client:
  ribbon:
    listOfServers: https://anime.anidub.life

jisedai-feign-client:
  ribbon:
    listOfServers: https://jisedai.tv

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 2
  retryableStatusCodes: 429, 403, 504, 503

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    com.netflix: ERROR
    nasirov.yv: DEBUG