application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter:
      enabled: true
  cache:
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  sse:
    timeout-in-min: 5
  auth:
    fandub-titles-service-basic-auth: ${FTS_BASIC_AUTH}
    mal-service-basic-auth: ${MS_BASIC_AUTH}
  common:
    enable-build-url-in-runtime: true

server:
  port: ${PORT}

sovet-romantica-feign-client:
  ribbon:
    ReadTimeout: 10000

shiza-project-feign-client:
  ribbon:
    ReadTimeout: 10000

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxAutoRetries: 4
  MaxAutoRetriesNextServer: 0

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    com.netflix: ERROR
    nasirov.yv: INFO