application:
  logo:
    name: anime-checker-logo.txt
  services:
    applicationLogoPrinter:
      enabled: true
  cache:
    sse:
      name: sse
      ttl: 300
      max-entity-count: 50
  common:
    enable-build-url-in-runtime: true
  feign:
    enabled: false
  web-client:
    enabled: true
    compress: true
    connection-timeout: 5s
    max-attempts: 5
    min-backoff: 100ms
    max-backoff: 1s
  external-services:
    fandub-titles-service-basic-auth: ${FTS_BASIC_AUTH}
    mal-service-basic-auth: ${MS_BASIC_AUTH}
    fandub-titles-service-url: https://fandub-titles-service.herokuapp.com/
    mal-service-url: https://mal-service.herokuapp.com/

server:
  port: ${PORT}

spring:
  application:
    name: anime-checker

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR