application:
  resources:
    applicationLogo: anime-checker-logo.txt
    tempFolder: temp
    tempRawReferences: tempRawReferences.json
    tempNewTitlesInAnimediaSearchList: newTitles.json
    tempRemovedTitlesFromAnimediaSearchList: removedTitles.json
    tempDuplicatedUrlsInAnimediaSearchList: titlesWithEqualsUrls.json
    tempReferencesWithInvalidMALTitleName: referencesWithInvalidMALTitleName.json
    tempExAnnouncements: exAnnouncements.json
  urls:
    animedia-urls:
      online-animedia-tv: https://online.animedia.tv/
    mal-urls:
      myAnimeList-net: https://myanimelist.net/
      cdn-myAnimeList-net: https://cdn.myanimelist.net/
  services:
    applicationLogoPrinter-enabled: true
  cron:
    resources-check-cron-expression: 0 0/30 * * * ?

server:
  port: ${PORT}

animedia-feign-client:
  ribbon:
    listOfServers: https://online.animedia.tv

animedia-api-feign-client:
  ribbon:
    listOfServers: https://ios.animedia.tv

mal-feign-client:
  ribbon:
    listOfServers: https://myanimelist.net/

github-feign-client:
  ribbon:
    listOfServers: https://raw.githubusercontent.com

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 2
  retryableStatusCodes: 429, 403, 504

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000