spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

starter-common:
  external-services:
    mal-access-service-url: http://localhost:8088/

starter-reactive-services:
  web-client:
    proxy-type: HTTP

starter-cache:
  type: CAFFEINE