spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: anime-checker

starter-reactive-services:
  web-client:
    read-timeout: 60s
    max-attempts: 1

starter-cache:
  enabled: true
  type: CAFFEINE
  caches:
    - name: ${application.cache-props.github-cache-name:}
      expire-after-write: 24h

management:
  endpoint:
    health:
      probes:
        enabled: true

application:
  cache-props:
    cache-on-startup: true
    github-cache-name: github
    github-cache-key: common-titles
  mal-props:
    offset-step: 300
    url: https://myanimelist.net
  enabled-fandub-sources:
    - AKARI_GROUP
    - AMBER
    - ANIBREEZE
    - ANIDUB
    - ANILIBRIA
    - ANIMEDIA
    - ANIME_BEST
    - ANIME_JET
    - ANI_FILM
    - ANI_MAUNT
    - ANI_NYA_TV
    - ANI_PLAGUE
    - ANI_PLAY_TV
    - ANI_RISE
    - ANYTHING_GROUP
    - DREAM_CAST
    - DUB_CLUB
    - FREE_DUB
    - FRONDA_STUDIO
    - FUMO_DUB
    - HARON_MEDIA
    - INSOMNIA_STUDIO
    - JAMCLUB
    - JISEDAI
    - JN_UNION
    - JUTSU
    - KALABS_STUDIO
    - KODIK
    - KOMNATA_DIDI
    - LE_PRODUCTION_TV
    - NINEANIME
    - SENU_PROJECT
    - SHIROI_KITSUNE
    - SOVETROMANTICA
    - STEP_ONEE
  ignore-next-episode-for-watch:
    - KODIK

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    nasirov.yv: INFO
    reactor.netty: ERROR