version: '3.7'

services:

  app:
    image: nasirov/anime-checker:debug
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
      - 8849:8849
    environment:
      - "JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions \
         -XX:+UseCGroupMemoryLimitForHeap \
         -Dfile.encoding=UTF-8 \
         -Djava.security.egd=file:/dev/./urandom \
         -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n \
         -agentpath:/usr/local/jprofiler10.1.5/bin/linux-x64/libjprofilerti.so=port=8849"
      - "PORT=8080"