<!DOCTYPE html>
<html lang="en">
<head>
  <title>Not Found.</title>
  <link rel="stylesheet" type="text/css" href="/css/ps2p.css"/>
  <link rel="stylesheet" type="text/css" href="/css/nes.min.css"/>
  <link rel="stylesheet" type="text/css" href="/css/common-style.css"/>
  <link rel="shortcut icon" type="image/x-icon" href="/img/faviconError.ico"/>
</head>
<body>
<div class="flex-wrapper height-full-vh">
  <div class="container">
    <h2>Whatever you were looking for was not found.</h2>
    <span>
            <a href="/">
                <button type="button" class="nes-btn is-dark-alt is-primary">Home</button>
            </a>
        </span>
  </div>
</div>
</body>
</html>