image:
  pullPolicy: Always
  registry: registry.gitlab.com/fandub/images
  name: anibozu
  tag: short-commit-hash
docker:
  progressDeadlineSeconds: 600
  containerPort: 8080
  pullSecretName: gitlab-registry-credentials
replicaCount: 1
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi
    cpu: 500m
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  hosts:
    - anibozu-backend.nasirov.info
  tls:
    hosts:
      - anibozu-backend.nasirov.info
    secretName: certificate-nasirov-info
  paths:
    - /(process/[\w-]{2,16}$)
vault:
  enabled: true
  secrets:
    - name: third-party-data-github
      path: third-party/data/github
      variables:
        - name: token
          bindTo: GITHUB_ACCESS_TOKEN