image:
  pullPolicy: Always
  registry: registry.gitlab.com/fandub/images
  name: anime-checker
  tag: short-commit-hash
docker:
  progressDeadlineSeconds: 600
  containerPort: 8080
  pullSecretName: gitlab-registry-credentials
replicaCount: 2
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 500Mi
    cpu: 500m
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  hosts:
    - anime-checker.nasirov.info
  tls:
    hosts:
      - anime-checker.nasirov.info
    secretName: certificate-nasirov-info
  paths:
    - /((?!((actuator))).*)