image:
  pullPolicy: Always
  registry: registry.gitlab.com/anime-project/images
  name: anibozu
  tag: short-commit-hash
docker:
  progressDeadlineSeconds: 600
  containerPort: 8080
  pullSecretName: gitlab-registry-credentials
replicaCount: 1
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 500Mi
    cpu: 500m
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: true
    nginx.ingress.kubernetes.io/limit-burst-multiplier: '1'
    nginx.ingress.kubernetes.io/limit-connections: '1'
    nginx.ingress.kubernetes.io/limit-rpm: '5'
    nginx.ingress.kubernetes.io/limit-rps: '1'
  hosts:
    - api.anibozu.fun
  paths:
    - /api/v1/user/[\w-]{2,16}/anime-list$
    - /api/v1/anime/\d+/episode/\d+$
vault:
  enabled: true
  secrets:
    - name: anibozu-data-admin
      path: anibozu/data/admin
      variables:
        - name: username
          bindTo: ANIBOZU_ADMIN_USERNAME
        - name: password
          bindTo: ANIBOZU_ADMIN_PASSWORD